FOOD_SEED = [
    {
        "name": "Grilled Chicken Breast",
        "calories": 165,
        "protein": 31,
        "carbs": 0,
        "fat": 3.6,
        "fiber": 0,
        "sodium": 74,
    },
    {
        "name": "Brown Rice (1 cup)",
        "calories": 216,
        "protein": 5,
        "carbs": 45,
        "fat": 1.8,
        "fiber": 3.5,
        "sodium": 10,
    },
    {
        "name": "Banana",
        "calories": 105,
        "protein": 1.3,
        "carbs": 27,
        "fat": 0.4,
        "fiber": 3.1,
        "sodium": 1,
    },
    {
        "name": "Greek Yogurt",
        "calories": 100,
        "protein": 17,
        "carbs": 6,
        "fat": 0.7,
        "fiber": 0,
        "sodium": 36,
    },
    {
        "name": "Salmon Fillet",
        "calories": 208,
        "protein": 20,
        "carbs": 0,
        "fat": 13,
        "fiber": 0,
        "sodium": 59,
    },
    {
        "name": "Avocado (half)",
        "calories": 120,
        "protein": 1.5,
        "carbs": 6,
        "fat": 11,
        "fiber": 5,
        "sodium": 5,
    },
    {
        "name": "Egg (boiled)",
        "calories": 78,
        "protein": 6,
        "carbs": 0.6,
        "fat": 5,
        "fiber": 0,
        "sodium": 62,
    },
    {
        "name": "Oatmeal (1 cup)",
        "calories": 154,
        "protein": 5,
        "carbs": 27,
        "fat": 2.6,
        "fiber": 4,
        "sodium": 2,
    },
    {
        "name": "Spinach (100g)",
        "calories": 23,
        "protein": 2.9,
        "carbs": 3.6,
        "fat": 0.4,
        "fiber": 2.2,
        "sodium": 79,
    },
    {
        "name": "Sweet Potato",
        "calories": 103,
        "protein": 2.3,
        "carbs": 24,
        "fat": 0.1,
        "fiber": 3.8,
        "sodium": 41,
    },
    {
        "name": "Almonds (28g)",
        "calories": 164,
        "protein": 6,
        "carbs": 6,
        "fat": 14,
        "fiber": 3.5,
        "sodium": 1,
    },
    {
        "name": "Whole Wheat Bread",
        "calories": 69,
        "protein": 3.6,
        "carbs": 12,
        "fat": 1,
        "fiber": 1.9,
        "sodium": 132,
    },

    # EXTRA

    {
        "name": "Apple",
        "calories": 95,
        "protein": 0.5,
        "carbs": 25,
        "fat": 0.3,
        "fiber": 4.4,
        "sodium": 2,
    },
    {
        "name": "Tuna (100g)",
        "calories": 132,
        "protein": 28,
        "carbs": 0,
        "fat": 1,
        "fiber": 0,
        "sodium": 37,
    },
    {
        "name": "Peanut Butter (2 tbsp)",
        "calories": 188,
        "protein": 8,
        "carbs": 6,
        "fat": 16,
        "fiber": 2,
        "sodium": 147,
    },
    {
        "name": "Broccoli (100g)",
        "calories": 35,
        "protein": 2.4,
        "carbs": 7,
        "fat": 0.4,
        "fiber": 3.3,
        "sodium": 41,
    },
    {
        "name": "Cheddar Cheese (30g)",
        "calories": 121,
        "protein": 7,
        "carbs": 1,
        "fat": 10,
        "fiber": 0,
        "sodium": 190,
    },
    {
        "name": "Pasta (1 cup cooked)",
        "calories": 220,
        "protein": 8,
        "carbs": 43,
        "fat": 1.3,
        "fiber": 2.5,
        "sodium": 1,
    },
    {
        "name": "White Rice (1 cup)",
        "calories": 205,
        "protein": 4.2,
        "carbs": 45,
        "fat": 0.4,
        "fiber": 0.6,
        "sodium": 1,
    },
    {
        "name": "Turkey Breast",
        "calories": 135,
        "protein": 30,
        "carbs": 0,
        "fat": 1,
        "fiber": 0,
        "sodium": 52,
    },
]

