name: CI

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # -------------------------
      # BACKEND
      # -------------------------
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install backend dependencies
        run: |
          cd backend
          pip install -r requirements.txt

      - name: Backend syntax check
        run: |
          cd backend
          python -m py_compile $(git ls-files '*.py')

      # -------------------------
      # FRONTEND
      # -------------------------
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Build frontend
        run: |
          cd frontend
          npm install
          npx vite build

      # -------------------------
      # DOCKER BUILD
      # -------------------------
      - name: Docker build (full app)
        run: docker build -t nutrition-app .
